# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MPI Tutorial
tagline:
url:              http://mpitutorial.com
baseurl:          ''
author:
  name:           Wes Kendall
  url:            https://github.com/wesleykendall/
  email:          wesleykendall@gmail.com
plugins:
  - jekyll-redirect-from

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wesleykendall/mpitutorial
  code:           https://github.com/wesleykendall/mpitutorial/tree/gh-pages
pages_list:
  Tutorials:    'tutorials'
  Recommended Books:    'recommended-books'
  About:                'about'
